### ISSUE TITLE
Front End Development Task

### ISSUE THREAD

**Issue by Itsmeshreyas** [Itsmeshreyas/Expense-Splitter#2]
1-Design UI pages and its flow

**Comment by Sonalipjadhav** [comment]
UI Diagram Uploaded
![Splitwise UI diagram](https://user-images.githubusercontent.com/106860472/181934496-271b1da3-a269-4f4d-9350-efbfd8732d79.png)

**Comment by suyogpandagare** [comment]
> 1-Design UI pages and its flow

UI Diagram Successfully Added
