### ISSUE TITLE
Back End Development Task

### ISSUE THREAD

**Issue by Itsmeshreyas** [Itsmeshreyas/Expense-Splitter#3]
1- Tables and their Relations
2-ER diagram

**Comment by Itsmeshreyas** [comment]
Conducted meeting and discovered  database entities and their attributes which are as following

1. Settlement
>  Amount
>  Mode of  transaction
>  Date
>  Group
>  No Group      

2. Expense
> Amount
> Event
> Event Participant
> Date
> Distribution
> File/photo

3. Dashboard    
> Total balance
> You borrowed
> You lend

**Comment by Itsmeshreyas** [comment]
First meeting in backend

**Comment by Abhilash1008** [comment]
Today's Task - Determined The DataBase Purposed and Discovered entities as follows:-
1) User
       -UserName
       -Email id
      -  Mobile No
      - UPI-ID
      - user password
      
2)Friend 
       - Friend-Name 
       - Email-Id 

3)Group
         -Group-Name
         -Members
         -Type

**Comment by Itsmeshreyas** [comment]
[Book1.xlsx](https://github.com/Itsmeshreyas/Expense-Splitter/files/9213290/Book1.xlsx)
[Book1.xlsx](https://github.com/Itsmeshreyas/Expense-Splitter/files/9276336/Book1.xlsx)

**Comment by Itsmeshreyas** [comment]
Created some basic Database tables !
Excel file attached

**Comment by Abhilash1008** [comment]
Database Tables like 
 1. User, 2.Group, 3.DashBoard, 4.User_Group_map, 5.GroupExpense, 6.InitialAmount, 7.Transaction.
are created.
